### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by russcam** [russcam/asciidocnet#5]
@dmetzgar, I was looking to do this today and see you have implemented this already in a fork at https://github.com/dmetzgar/asciidocnet. Would you be happy to open a PR to pull into here?

**Comment by dmetzgar** [comment]
The source code is ported. And I ported most of the tests. But I converted the tests to use xUnit as an exercise to get more familiar with xUnit. I dropped all the specflow stuff since it doesn't work on core. I will make the PR so you can have a look at the changes.

**Comment by dmetzgar** [comment]
PR #6 is submitted. It also addresses #4. If you're looking to target both .NET Framework and Core I can make some adjustments to the PR.

**Comment by russcam** [comment]
Awesome, thanks @dmetzgar; I'll take a look :+1:

**Comment by russcam** [comment]
Support has been implemented as part of #6
